Removing interactive prompts

diff --git a/git-secrets b/git-secrets
--- a/git-secrets
+++ b/git-secrets
@@ -16,12 +16,11 @@ to install hooks to a git repository in the working directory.
 d,dir=      Optional path to a repository for which to install hooks
 h,help    show help message"
 declare -r SCAN_SPEC="\
-git secrets scan (-f | --file ...) [-n|--non-interactive]
+git secrets scan (-f | --file ...)
 
 Scans the given file for a list of prohibited patterns.
 --
 f,file=           Path to a file to scan for secrets. Pass - to scan stdin.
-n,non-interactive Do not prompt for user input intervention on failures.
 h,help            show help message"
 declare -r NO_PATTERNS_WARNING_MSG="\
 No prohibited patterns have been defined
@@ -42,10 +41,6 @@ declare -r PROHIBITED_ERROR_MSG="\
 [ERROR] Matched prohibited patterns
 "
 
-warn_if_no_patterns() {
-  [ -z "$PATTERNS" ] && say "$NO_PATTERNS_WARNING_MSG"
-}
-
 check_pattern() {
   local pattern="$1" filename="$2" grep_cmd=$(git config --get secrets.grep)
   # Ensure the grep command is valid and executable.
@@ -54,42 +49,18 @@ check_pattern() {
   GREP_OPTIONS='' $grep_cmd -nw -H -e "${pattern}" "${filename}"
 }
 
-should_fail() {
-  local pattern=$1 file=$2
-  local -r affirmative="Yes: this is a false positive, allow it and continue."
-  local -r negative="No: this is a secret. Do not commit it and stop."
-  echo $'\n'"^^^ Matched prohibited pattern in ${file}: ${pattern}"
-  echo "Do you wish to commit this anyway?"
-  select yn in "${negative}" "${affirmative}"; do
-    case $yn in
-      [nN]*) return 0 ;;
-      [Y]*) echo; return 1 ;;
-    esac
-  done
-}
-
 scan() {
   local -r filename="$1"
-  warn_if_no_patterns
-  if [ ! -z "$PATTERNS" ]; then
-    if [ $NON_INTERACTIVE -eq 1 ]; then
-      # Check will all patterns at once
-      check_pattern "$PATTERNS" "${filename}" && return 1
-    else
-      # Check each pattern individually for user prompts.
-      local found_errors=0
-      for pattern in $PATTERNS; do
-        if check_pattern "${pattern}" "${filename}"; then
-          should_fail "${pattern}" "${filename}" && return 1
-        fi
-      done
-    fi
+  if [ -z "$PATTERNS" ]; then
+    say "$NO_PATTERNS_WARNING_MSG"
+  else
+    check_pattern "$PATTERNS" "${filename}" && return 1
   fi
   return 0
 }
 
 commit_msg_hook() {
-  scan "$1" || die "$PROHIBITED_ERROR_MSG"
+  scan "$1" || die "(commit-msg)" $'\n' "$PROHIBITED_ERROR_MSG"
 }
 
 # NOTE: This is based on git's pre-commit.sample script.
@@ -107,7 +78,7 @@ pre_commit_hook() {
   for file in $changes; do
     scan "$file" || found_match=1
   done
-  [ $found_match -eq 1 ] && die "$PROHIBITED_ERROR_MSG"
+  [ $found_match -eq 1 ] && die "(pre-commit)" $'\n' "$PROHIBITED_ERROR_MSG"
 }
 
 # Determines if merging in a commit will introduce tainted history.
@@ -120,7 +91,8 @@ prepare_commit_msg_hook() {
       local dest="${branch#refs/heads/}"    # cut out "refs/heads"
       echo "Checking if merging ${sha} into ${dest} adds prohibited history"
       git log "${dest}".."${sha}" -p \
-        | "$0" scan -f - -n || die "$PROHIBITED_ERROR_MSG"
+        | "$0" scan -f - -n \
+        || die "(prepare-commit-msg)" $'\n' "$PROHIBITED_ERROR_MSG"
       ;;
     *) ;;
   esac
@@ -167,10 +139,6 @@ install_hooks() {
 COMMAND="${1:--h}"
 NONGIT_OK=1
 LOAD_GIT="$(git --exec-path)/git-sh-setup"
-[[ -t 0 && -t 1 ]] && declare -r IS_ATTY=1 || declare -r IS_ATTY=0
-[ "$(git config --get secrets.non-interactive)" == '1' ] \
-  && NON_INTERACTIVE=1 \
-  || NON_INTERACTIVE=0
 shift
 
 case "$COMMAND" in
@@ -183,24 +151,9 @@ case "$COMMAND" in
   scan)
     OPTIONS_SPEC="$SCAN_SPEC"
     . $LOAD_GIT
-    declare file
-    while [ $# -gt 0 ]; do
-      case "$1" in
-        -f) shift; file="$1"; shift ;;
-        -n) shift; NON_INTERACTIVE=1 ;;
-        --) break ;;
-      esac
-    done
-    [ -z "$file" ] && die "-f | --file is required"
-    # Interactive mode is only allowed when input is not piped in as "-"
-    if [ "$file" == '-' ]; then
-      NON_INTERACTIVE=1
-    elif [ ! -f "$file" ]; then
-      die "File not found: $file"
-    fi
-    [ "$IS_ATTY" -eq 0 ] && [ "$NON_INTERACTIVE" -eq 0 ] && exec < /dev/tty
-    scan "$file" || die "$PROHIBITED_ERROR_MSG"
-    exit 0
+    [ -z "$2" ] && die "-f | --file is required"
+    [ "$2" != '-' ] && [ ! -f "$2" ] && die "File not found: $2"
+    scan "$2" || die "$PROHIBITED_ERROR_MSG"
     ;;
   install)
     OPTIONS_SPEC="$INSTALL_SPEC"
