Clean up using linter feedback

diff --git a/git-secrets b/git-secrets
--- a/git-secrets
+++ b/git-secrets
@@ -12,6 +12,11 @@
 # express or implied. See the License for the specific language governing
 # permissions and limitations under the License.
 
+# Exit when a command fails.
+set -e
+# Show help if no arguments are provided.
+[ $# -eq 0 ] && set -- -h
+
 export NONGIT_OK=1 # Used in git-sh-setup
 export OPTIONS_SPEC="\
 git secrets --scan [-r|--recursive] [--cached] [--no-index] [--untracked] [<files>...]
@@ -53,7 +58,8 @@ load_patterns() {
     # Only split words on '\n\t ' and strip "\r" from the output to account
     # for carriage returns being added on Windows systems. Note that this
     # trimming is done before the test to ensure that the string is not empty.
-    local result="$(export IFS=$'\n\t '; $cmd | tr -d $'\r')"
+    local result
+    result="$(export IFS=$'\n\t '; $cmd | tr -d $'\r')"
     # Do not add empty lines from providers as that would match everything.
     if [ -n "${result}" ]; then
       echo "${result}"
@@ -63,45 +69,48 @@ load_patterns() {
 
 load_allowed() {
   git config --get-all secrets.allowed
-  local gitallowed="$(git rev-parse --show-toplevel)/.gitallowed"
+  local gitallowed
+  gitallowed="$(git rev-parse --show-toplevel)/.gitallowed"
   if [ -e "$gitallowed" ]; then
-    cat $gitallowed | awk 'NF && $1!~/^#/'
+    awk 'NF && $1!~/^#/' < "$gitallowed"
   fi
 }
 
 # load patterns and combine them with |
 load_combined_patterns() {
-  local patterns=$(load_patterns)
-  local combined_patterns=''
+  local patterns combined_patterns=''
+  patterns=$(load_patterns)
   for pattern in $patterns; do
     combined_patterns=${combined_patterns}${pattern}"|"
   done
   combined_patterns=${combined_patterns%?}
-  echo $combined_patterns
+  echo "${combined_patterns}"
 }
 
 # Scans files or a repo using patterns.
 scan() {
-  local files="$1" options=""
-  [ "${SCAN_CACHED}" == 1 ] && options+="--cached"
-  [ "${SCAN_UNTRACKED}" == 1 ] && options+=" --untracked"
-  [ "${SCAN_NO_INDEX}" == 1 ] && options+=" --no-index"
+  local files="$1"
+  local options=( )
+  [ "${SCAN_CACHED}" == 1 ] && options+=("--cached")
+  [ "${SCAN_UNTRACKED}" == 1 ] && options+=("--untracked")
+  [ "${SCAN_NO_INDEX}" == 1 ] && options+=("--no-index")
   # Scan using git-grep if there are no files or if git options are applied.
-  if [ -z "${files}" ] || [ ! -z "${options}" ]; then
-    output=$(git_grep $options $files)
+  if [ -z "${files}" ] || [ ! -z $options ]; then
+    output=$(git_grep "${options[@]}" "${files[@]}")
   else
-    output=$(regular_grep $files)
+    output=$(regular_grep "${files[@]}")
   fi
   process_output $? "${output}"
 }
 
 # Scans through history using patterns
 scan_history() {
+  local combined_patterns to_scan
   # git log does not support multiple patterns, so we need to combine them
-  local combined_patterns=$(load_combined_patterns)
+  combined_patterns=$(load_combined_patterns)
   [ -z "${combined_patterns}" ] && return 0
   # Looks for differences matching the patterns, reduces the number of revisions to scan
-  local to_scan=$(git log --all -G"${combined_patterns}" --pretty=%H)
+  to_scan=$(git log --all -G "${combined_patterns}" --pretty=%H)
   # Scan through revisions with findings to normalize output
   output=$(git_grep "" "${to_scan}")
   process_output $? "${output}"
@@ -110,36 +119,42 @@ scan_history() {
 # Performs a git-grep, taking into account patterns and options.
 # Note: this function returns 1 on success, 0 on error.
 git_grep() {
-  local options="$1"; shift
-  local files=$@ combined_patterns=$(load_combined_patterns)
+  local options files combined_patterns
+  options="$1"; shift
+  files=( $@ )
+  combined_patterns=$(load_combined_patterns)
   [ -z "${combined_patterns}" ] && return 1
-  GREP_OPTIONS= LC_ALL=C git grep -nwHEI ${options} "${combined_patterns}" $files
+  # Note that options and files are not quoted as we want to use splitting.
+  GREP_OPTIONS='' LC_ALL=C git grep -nwHEI ${options} "${combined_patterns}" "${files[@]}"
 }
 
 # Performs a regular grep, taking into account patterns and recursion.
 # Note: this function returns 1 on success, 0 on error.
 regular_grep() {
-  local files=$@ patterns=$(load_patterns) action='skip'
+  local files patterns action
+  files="$*"
+  action='skip'
+  patterns=$(load_patterns)
   [ -z "${patterns}" ] && return 1
   [ ${RECURSIVE} -eq 1 ] && action="recurse"
-  GREP_OPTIONS= LC_ALL=C grep -d "${action}" -nwHEI "${patterns}" $files
+  GREP_OPTIONS='' LC_ALL=C grep -d "${action}" -nwHEI "${patterns}" "${files}"
 }
 
 # Process the given status ($1) and output variables ($2).
 # Takes into account allowed patterns, and if a bad match is found,
 # prints an error message and exits 1.
 process_output() {
-  local status="$1" output="$2"
-  local allowed=$(load_allowed)
+  local status="$1" output="$2" allowed
+  allowed=$(load_allowed)
   case "$status" in
     0)
       [ -z "${allowed}" ] && echo "${output}" && return 1
       # Determine with a negative grep if the found matches are allowed
-      echo "${output}" | GREP_OPTIONS= LC_ALL=C grep -Ev "${allowed}" \
+      echo "${output}" | GREP_OPTIONS='' LC_ALL=C grep -Ev "${allowed}" \
         && return 1 || return 0
       ;;
     1) return 0 ;;
-    *) exit $status
+    *) exit "$status"
   esac
 }
 
@@ -169,7 +184,7 @@ commit_msg_hook() {
 # Scans all files that are about to be committed.
 pre_commit_hook() {
   SCAN_CACHED=1
-  local file found_match=0 rev="4b825dc642cb6eb9a060e54bf8d69288fbee4904"
+  local rev="4b825dc642cb6eb9a060e54bf8d69288fbee4904"
   # Diff against HEAD if this is not the first commit in the repo.
   git rev-parse --verify HEAD >/dev/null 2>&1 && rev="HEAD"
   # Filter out deleted files using --diff-filter
@@ -180,10 +195,11 @@ pre_commit_hook() {
 prepare_commit_msg_hook() {
   case "$2,$3" in
     merge,)
-      local git_head=$(env | grep GITHEAD)  # e.g. GITHEAD_<sha>=release/1.43
-      local sha="${git_head##*=}"           # Get just the SHA
-      local branch=$(git symbolic-ref HEAD) # e.g. refs/heads/master
-      local dest="${branch#refs/heads/}"    # cut out "refs/heads"
+      local git_head sha branch dest
+      git_head=$(env | grep GITHEAD)  # e.g. GITHEAD_<sha>=release/1.43
+      sha="${git_head##*=}"           # Get just the SHA
+      branch=$(git symbolic-ref HEAD) # e.g. refs/heads/master
+      dest="${branch#refs/heads/}"    # cut out "refs/heads"
       git log "${dest}".."${sha}" -p | scan_with_fn_or_die "scan" -
       ;;
   esac
@@ -214,15 +230,15 @@ install_all_hooks() {
 # Adds a git config pattern, ensuring to de-dupe
 add_config() {
   local key="$1"; shift
-  local value="$@"
+  local value="$*"
   if [ ${LITERAL} -eq 1 ]; then
     value=$(sed 's/[\.|$(){}?+*^]/\\&/g' <<< "${value}")
   fi
   if [ ${GLOBAL} -eq 1 ]; then
-    git config --global --get-all $key | grep -Fq "${value}" && return 1
+    git config --global --get-all "${key}" | grep -Fq "${value}" && return 1
     git config --global --add "${key}" "${value}"
   else
-    git config --get-all $key | grep -Fq "${value}" && return 1
+    git config --get-all "${key}" | grep -Fq "${value}" && return 1
     git config --add "${key}" "${value}"
   fi
 }
@@ -311,7 +327,6 @@ if [ ${RECURSIVE} -eq 1 ]; then
 fi
 
 case "${COMMAND}" in
-  -h|--help|--) "$0" -h; exit 0 ;;
   --add-provider) add_config "secrets.providers" "$@" ;;
   --register-aws) register_aws ;;
   --aws-provider) aws_provider "$1" ;;
