Refactoring for better code reuse

diff --git a/git-secrets b/git-secrets
--- a/git-secrets
+++ b/git-secrets
@@ -53,30 +53,51 @@ load_patterns() {
   done
 }
 
-scan_history() {
-  scan "$(git rev-list --all)"
-}
-
+# Scans files or a repo using patterns.
 scan() {
-  local files="$1" action='skip' patterns=$(load_patterns)
-  local allowed=$(git config --get-all secrets.allowed)
-  # No need to scan anything if there are no prohibited patterns.
-  [ -z "${patterns}" ] && return 0
-  # Build up the options to use when scanning with git-grep.
-  local options=""
+  local files="$1" options=""
   [ "${SCAN_CACHED}" == 1 ] && options+="--cached"
   [ "${SCAN_UNTRACKED}" == 1 ] && options+=" --untracked"
   [ "${SCAN_NO_INDEX}" == 1 ] && options+=" --no-index"
   # Scan using git-grep if there are no files or if git options are applied.
   if [ -z "${files}" ] || [ ! -z "${options}" ]; then
-    # Note: Passing an empty list of files will scan the entire repo.
-    output=$(GREP_OPTIONS= LC_ALL=C git grep -nwHE ${options} "${patterns}" ${files})
+    output=$(git_grep $options $files)
   else
-    # -r only applies when file paths are provided.
-    [ "${RECURSIVE}" -eq 1 ] && action="recurse"
-    output=$(GREP_OPTIONS= LC_ALL=C grep -d $action -nwHE "${patterns}" $files)
+    output=$(regular_grep $files)
   fi
-  local status=$?
+  process_output $? "${output}"
+}
+
+scan_history() {
+  local to_scan=$(git rev-list --all)
+  local output=$(git_grep "" "${to_scan}")
+  process_output $? "${output}"
+}
+
+# Performs a git-grep, taking into account patterns and options.
+# Note: this function returns 1 on success, 0 on error.
+git_grep() {
+  local options="$1"; shift
+  local files=$@ patterns=$(load_patterns)
+  [ -z "${patterns}" ] && return 1
+  GREP_OPTIONS= LC_ALL=C git grep -nwHE ${options} "${patterns}" $@
+}
+
+# Performs a regular grep, taking into account patterns and recursion.
+# Note: this function returns 1 on success, 0 on error.
+regular_grep() {
+  local files=$@ patterns=$(load_patterns) action='skip'
+  [ -z "${patterns}" ] && return 1
+  [ "${RECURSIVE}" -eq 1 ] && action="recurse"
+  GREP_OPTIONS= LC_ALL=C grep -d "${action}" -nwHE "${patterns}" $@
+}
+
+# Process the given status ($1) and output variables ($2).
+# Takes into account allowed patterns, and if a bad match is found,
+# prints an error message and exits 1.
+process_output() {
+  local status="$1" output="$2"
+  local allowed=$(git config --get-all secrets.allowed)
   case "$status" in
     0)
       [ -z "${allowed}" ] && echo "${output}" && return 1
@@ -89,7 +110,7 @@ scan() {
   esac
 }
 
-# Calls the given scanning function.
+# Calls the given scanning function at $1, shifts, and passes to it $@.
 # Exit 0 if success, otherwise exit 1 with error message.
 scan_with_fn_or_die() {
   local fn="$1"; shift
