Implemented scan-history

diff --git a/git-secrets b/git-secrets
--- a/git-secrets
+++ b/git-secrets
@@ -14,6 +14,7 @@
 
 NONGIT_OK=1 OPTIONS_SPEC="\
 git secrets --scan [-r|--recursive] [<files>...]
+git secrets --scan-history
 git secrets --install [-f|--force] [<target-directory>]
 git secrets --list [--global]
 git secrets --add [-a|--allowed] [-l|--literal] [--global] <pattern>
@@ -22,6 +23,7 @@ git secrets --register-aws [--global]
 git secrets --aws-provider [<credentials-file>]
 --
 scan Scans <files> for prohibited patterns
+scan-history Scans repo for prohibited patterns
 install Installs git hooks for Git repository or Git template directory
 list Lists secret patterns
 add Adds a prohibited or allowed pattern, ensuring to de-dupe with existing patterns
@@ -48,6 +50,25 @@ load_patterns() {
   done
 }
 
+scan_history() {
+  local action='skip' patterns=$(load_patterns)
+  local allowed=$(git config --get-all secrets.allowed)
+  [ -z "${patterns}" ] && return 0
+  local rev_list=$(git rev-list --all)
+  output=$(GREP_OPTIONS= LC_ALL=C git grep -nwHE "${patterns}" $rev_list)
+  local status=$?
+  case "$status" in
+    0)
+      [ -z "${allowed}" ] && echo "${output}" && return 1
+      # Determine with a negative grep if the found matches are allowed
+      echo "${output}" | GREP_OPTIONS= LC_ALL=C grep -Ev "${allowed}" \
+        && return 1 || return 0
+      ;;
+    1) return 0 ;;
+    *) exit $status
+  esac
+}
+
 scan() {
   local files="$1" action='skip' patterns=$(load_patterns)
   local allowed=$(git config --get-all secrets.allowed)
@@ -70,6 +91,19 @@ scan() {
     1) return 0 ;;
     *) exit $status
   esac
+}
+
+scan_history_or_die() {
+  scan_history "$@" && exit 0
+  echo
+  echo "[ERROR] Matched one or more prohibited patterns"
+  echo
+  echo "Possible mitigations:"
+  echo "- Mark false positives as allowed using: git config --add secrets.allowed ..."
+  echo "- List your configured patterns: git config --get-all secrets.patterns"
+  echo "- List your configured allowed patterns: git config --get-all secrets.allowed"
+  echo "- Use --no-verify if this is a one-time false positive"
+  exit 1
 }
 
 scan_or_die() {
@@ -204,6 +238,7 @@ case "${COMMAND}" in
     fi
     ;;
   --scan) scan_or_die "$@" ;;
+  --scan-history) scan_history_or_die "$@" ;;
   --list)
     if [ "${GLOBAL}" -eq 1 ]; then
       git config --global --get-regex secrets.*
