Adding the ability to ignore false positives
This commit adds the ability to ignore false positives by defining
"allowed" regular expressions that are matched against any matched
prohibited patterns.

This commit also removes the ability to customize grep. We are simply
using egrep now.

Other changes:

- General cleaning up
- Renaming secrets.pattern to secrets.patterns
- Added the exclusion of example keys

diff --git a/git-secrets b/git-secrets
--- a/git-secrets
+++ b/git-secrets
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
-declare -r PATTERNS="$(git config --get-all secrets.pattern)"
-
+declare -r PATTERNS="$(git config --get-all secrets.patterns)"
+declare -r ALLOWED_PATTERNS="$(git config --get-all secrets.allowed)"
 declare -r MAIN_SPEC="\
 usage: git secrets scan [--file=]
    or: git secrets install [--repo=]
@@ -30,43 +30,47 @@ declare -r PROHIBITED_MSG="\
 
 [ERROR] Matched prohibited pattern
 
-- Use --no-verify if this is a false positive.
-- List your configured secrets using: git config --get-all secrets.pattern
+Possible mitigations:
+
+- Mark false positives as allowed using: git config --add secrets.allowed ...
+- List your configured patterns: git config --get-all secrets.patterns
+- List your configured allowed patterns: git config --get-all secrets.allowed
+- Use --no-verify if this is a one-time false positive
 "
 
 check_pattern() {
-  local pattern="$1" filename="$2" grep_cmd=$(git config --get secrets.grep)
-  [ "${grep_cmd}" == '' ] && grep_cmd="egrep -nwH"
-  GREP_OPTIONS= LC_ALL=C $grep_cmd "${pattern}" "${filename}"
+  local -r pattern="$1" filename="$2" inverse="$3"
+  if [ -z "${inverse}" ]; then
+    GREP_OPTIONS= LC_ALL=C grep -nwHE "${pattern}" "${filename}"
+  else
+    # Extract matches then determine with a negative grep if they're allowed.
+    GREP_OPTIONS= LC_ALL=C grep -nwHE "${pattern}" "${filename}" \
+      | GREP_OPTIONS= LC_ALL=C grep -Ev "${inverse}"
+  fi
 }
 
 scan() {
-  [ ! -z "$PATTERNS" ] \
-    && check_pattern "${PATTERNS}" "$1" \
-    && return 1
-  return 0
+  [ -z "${PATTERNS}" ] && return 0
+  if [ -z "${ALLOWED_PATTERNS}" ]; then
+    check_pattern "${PATTERNS}" $1 && return 1 || return 0
+  fi
+  check_pattern "${PATTERNS}" $1 "${ALLOWED_PATTERNS}" && return 1 || return 0
 }
 
 commit_msg_hook() {
   scan "$1" || die "(commit-msg)" $'\n' "$PROHIBITED_MSG"
 }
 
-# NOTE: This is based on git's pre-commit.sample script.
-# Allows the hook to reject commits for brand new repos.
-determine_rev_to_diff() {
-  [ git rev-parse --verify HEAD >/dev/null 2>&1 ] \
-    && "HEAD" || echo "4b825dc642cb6eb9a060e54bf8d69288fbee4904"
-}
-
 # Scans a commit for prohibited patterns.
 pre_commit_hook() {
-  local file found_match=0 against=$(determine_rev_to_diff)
-  local changes=$(git diff-index --name-status --cached $against -- | cut -c3-)
-  found_match=0
-  for file in $changes; do
+  local file found_match=0 rev="4b825dc642cb6eb9a060e54bf8d69288fbee4904"
+  # Diff against HEAD if this is not the first commit in the repo.
+  [ git rev-parse --verify HEAD >/dev/null 2>&1 ] && rev="HEAD"
+  for file in $(git diff-index --name-status --cached $rev -- | cut -c3-); do
     scan "$file" || found_match=1
   done
-  [ $found_match -eq 1 ] && die "(pre-commit)" $'\n' "$PROHIBITED_MSG"
+  [ $found_match -eq 0 ] && exit 0
+  die "(pre-commit)" $'\n' "$PROHIBITED_MSG"
 }
 
 # Determines if merging in a commit will introduce tainted history.
@@ -123,36 +127,29 @@ install_hooks() {
 # Dispatch to the appropriate functions
 #######################################################################
 
-COMMAND="${1:--h}"
-NONGIT_OK=1
-LOAD_GIT="$(git --exec-path)/git-sh-setup"
-shift
+CMD="${1:--h}"; shift
+# Determine the approriate options spec and load git-sh helpers.
+[ "$CMD" == 'scan' ] && OPTIONS_SPEC="$SCAN_SPEC"
+[ "$CMD" == 'install' ] && OPTIONS_SPEC="$INSTALL_SPEC"
+NONGIT_OK=1 # Allow the command to run outside of a git repo.
+. $(git --exec-path)/git-sh-setup
 
-case "$COMMAND" in
-  -h) printf "$MAIN_SPEC\n" && exit 0 ;;
-  commit_msg_hook|pre_commit_hook|prepare_commit_msg_hook)
-    . $LOAD_GIT
-    $COMMAND "$@"
-    exit 0
-    ;;
+case "$CMD" in
   scan)
-    OPTIONS_SPEC="$SCAN_SPEC"
-    . $LOAD_GIT
-    [ -z "$2" ] && die "-f | --file is required"
+    [ "$1" != '-f' ] && die "-f | --file is required"
     [ "$2" != '-' ] && [ ! -f "$2" ] && die "File not found: $2"
-    scan "$2" || die "$PROHIBITED_MSG"
-    exit 0
+    scan "$2" || die "${PROHIBITED_MSG}"
     ;;
   install)
-    OPTIONS_SPEC="$INSTALL_SPEC"
-    . $LOAD_GIT
     case "$1" in
       --) dir=$(git rev-parse --show-toplevel) || die "Not in a git repo" ;;
-      -d|--dir) dir="$2" ;;
+      -d) dir="$2" ;;
       *) say "Invalid argument"; "$0" install -h; exit 129 ;;
     esac
     [ ! -d "${dir}" ] && die "Directory not found: ${dir}"
     install_hooks "${dir}"
     ;;
-  *) echo "Unknown command: $COMMAND" && "$0" -h && exit 129 ;;
+  commit_msg_hook|pre_commit_hook|prepare_commit_msg_hook) $CMD "$@" ;;
+  -h) printf "$MAIN_SPEC\n" ;;
+  *) echo "Unknown command: $CMD" && "$0" -h && exit 129 ;;
 esac
