Refactoring for better code reuse

diff --git a/git-secrets b/git-secrets
--- a/git-secrets
+++ b/git-secrets
@@ -61,38 +61,58 @@ load_allowed() {
   fi
 }
 
+# Scans files or a repo using patterns.
+scan() {
+  local files="$1" options=""
+  [ "${SCAN_CACHED}" == 1 ] && options+="--cached"
+  [ "${SCAN_UNTRACKED}" == 1 ] && options+=" --untracked"
+  [ "${SCAN_NO_INDEX}" == 1 ] && options+=" --no-index"
+  # Scan using git-grep if there are no files or if git options are applied.
+  if [ -z "${files}" ] || [ ! -z "${options}" ]; then
+    output=$(git_grep $options $files)
+  else
+    output=$(regular_grep $files)
+  fi
+  process_output $? "${output}"
+}
+
 # Scans through history using patterns
 scan_history() {
   # git log does not support multiple patterns, so we need to combine them
   local combined_patterns=$(load_combined_patterns)
   [ -z "${combined_patterns}" ] && return 0
-  # Looks for differences matching the patterns, reduces the number of revisions to scan
+  # Looks for differences matching the patterns, reduces the number of
+  # revisions to scan
   local to_scan=$(git log --all -G"${combined_patterns}" --pretty=%H)
   # Scan through revisions with findings to normalize output
   output=$(git_grep "" "${to_scan}")
   process_output $? "${output}"
 }
 
-scan() {
-  local files="$1" action='skip' patterns=$(load_patterns)
-  local allowed=$(load_allowed)
-  # No need to scan anything if there are no prohibited patterns.
-  [ -z "${patterns}" ] && return 0
-  # Build up the options to use when scanning with git-grep.
-  local options=""
-  [ "${SCAN_CACHED}" == 1 ] && options+="--cached"
-  [ "${SCAN_UNTRACKED}" == 1 ] && options+=" --untracked"
-  [ "${SCAN_NO_INDEX}" == 1 ] && options+=" --no-index"
-  # Scan using git-grep if there are no files or if git options are applied.
-  if [ -z "${files}" ] || [ ! -z "${options}" ]; then
-    # Note: Passing an empty list of files will scan the entire repo.
-    output=$(GREP_OPTIONS= LC_ALL=C git grep -nwHE ${options} "${patterns}" ${files})
-  else
-    # -r only applies when file paths are provided.
-    [ "${RECURSIVE}" -eq 1 ] && action="recurse"
-    output=$(GREP_OPTIONS= LC_ALL=C grep -d $action -nwHE "${patterns}" $files)
-  fi
-  local status=$?
+# Performs a git-grep, taking into account patterns and options.
+# Note: this function returns 1 on success, 0 on error.
+git_grep() {
+  local options="$1"; shift
+  local files=$@ patterns=$(load_patterns)
+  [ -z "${patterns}" ] && return 1
+  GREP_OPTIONS= LC_ALL=C git grep -nwHE ${options} "${patterns}" $@
+}
+
+# Performs a regular grep, taking into account patterns and recursion.
+# Note: this function returns 1 on success, 0 on error.
+regular_grep() {
+  local files=$@ patterns=$(load_patterns) action='skip'
+  [ -z "${patterns}" ] && return 1
+  [ "${RECURSIVE}" -eq 1 ] && action="recurse"
+  GREP_OPTIONS= LC_ALL=C grep -d "${action}" -nwHE "${patterns}" $@
+}
+
+# Process the given status ($1) and output variables ($2).
+# Takes into account allowed patterns, and if a bad match is found,
+# prints an error message and exits 1.
+process_output() {
+  local status="$1" output="$2"
+  local allowed=$(git config --get-all secrets.allowed)
   case "$status" in
     0)
       [ -z "${allowed}" ] && echo "${output}" && return 1
@@ -105,7 +125,7 @@ scan() {
   esac
 }
 
-# Calls the given scanning function.
+# Calls the given scanning function at $1, shifts, and passes to it $@.
 # Exit 0 if success, otherwise exit 1 with error message.
 scan_with_fn_or_die() {
   local fn="$1"; shift
