Fix issue #58, errors should be directed to stderr

diff --git a/git-secrets b/git-secrets
--- a/git-secrets
+++ b/git-secrets
@@ -132,9 +132,9 @@ process_output() {
   local allowed=$(load_allowed)
   case "$status" in
     0)
-      [ -z "${allowed}" ] && echo "${output}" && return 1
+      [ -z "${allowed}" ] && echo "${output}" >&2 && return 1
       # Determine with a negative grep if the found matches are allowed
-      echo "${output}" | GREP_OPTIONS= LC_ALL=C grep -Ev "${allowed}" \
+      echo "${output}" | GREP_OPTIONS= LC_ALL=C grep -Ev "${allowed}" >&2 \
         && return 1 || return 0
       ;;
     1) return 0 ;;
@@ -147,16 +147,16 @@ process_output() {
 scan_with_fn_or_die() {
   local fn="$1"; shift
   $fn "$@" && exit 0
-  echo
-  echo "[ERROR] Matched one or more prohibited patterns"
-  echo
-  echo "Possible mitigations:"
-  echo "- Mark false positives as allowed using: git config --add secrets.allowed ..."
-  echo "- Mark false positives as allowed by adding regular expressions to .gitallowed at repository's root directory"
-  echo "- List your configured patterns: git config --get-all secrets.patterns"
-  echo "- List your configured allowed patterns: git config --get-all secrets.allowed"
-  echo "- List your configured allowed patterns in .gitallowed at repository's root directory"
-  echo "- Use --no-verify if this is a one-time false positive"
+  echo >&2
+  echo "[ERROR] Matched one or more prohibited patterns" >&2
+  echo >&2
+  echo "Possible mitigations:" >&2
+  echo "- Mark false positives as allowed using: git config --add secrets.allowed ..." >&2
+  echo "- Mark false positives as allowed by adding regular expressions to .gitallowed at repository's root directory" >&2
+  echo "- List your configured patterns: git config --get-all secrets.patterns" >&2
+  echo "- List your configured allowed patterns: git config --get-all secrets.allowed" >&2
+  echo "- List your configured allowed patterns in .gitallowed at repository's root directory" >&2
+  echo "- Use --no-verify if this is a one-time false positive" >&2
   exit 1
 }
 
