Refactoring to be more like other git subcommands
This commit updates git-secrets to be more like other git subcommands.
Most git subcommands use options ("--option") when subcommands need
subcommands. In the case of git-secrets, we have --scan and --install.
The tool has now been refactored to accept the command as the first
option.

Other added features:
- You can now scan multiple files: git secrets scan path/to/files/*
- Now installs a readme

diff --git a/git-secrets b/git-secrets
--- a/git-secrets
+++ b/git-secrets
@@ -1,34 +1,9 @@
 #!/usr/bin/env bash
 declare -r PATTERNS="$(git config --get-all secrets.patterns)"
 declare -r ALLOWED_PATTERNS="$(git config --get-all secrets.allowed)"
-declare -r MAIN_SPEC="\
-usage: git secrets scan [--file=]
-   or: git secrets install [--repo=]
-
-   scan       Scans a file for prohibited patterns
-   install    Installs git hooks for a repository"
-
-declare -r INSTALL_SPEC="\
-git secrets install [(-d | --dir=...)] [-h|--help]
-
-Installs pre-commit and commit-msg hooks for the given repository.
-If no repository argument is provided, then the command attempts
-to install hooks to a git repository in the working directory.
---
-d,dir=      Optional path to a repository for which to install hooks
-h,help    show help message"
-
-declare -r SCAN_SPEC="\
-git secrets scan (-f | --file ...)
-
-Scans the given file for a list of prohibited patterns.
---
-f,file=           Path to a file to scan for secrets. Pass - to scan stdin.
-h,help            show help message"
-
 declare -r PROHIBITED_MSG="\
 
-[ERROR] Matched prohibited pattern
+[ERROR] Matched one or more prohibited patterns
 
 Possible mitigations:
 
@@ -37,40 +12,62 @@ Possible mitigations:
 - List your configured allowed patterns: git config --get-all secrets.allowed
 - Use --no-verify if this is a one-time false positive
 "
+declare -r NONGIT_OK=1 OPTIONS_SPEC="\
+git secrets --scan <files>...
+git secrets --install [-d | --dir=<repo>]
+--
+h,help     Show help message
+scan       Scans <files> for prohibited patterns
+install    Installs git hooks for repo
+d,dir=     Used with --install to specify the path to repo
+commit_msg_hook* commit-msg hook (internal only)
+pre_commit_hook* pre-commit hook (internal only)
+prepare_commit_msg_hook* prepare-commit-msg hook (internal only)"
 
-check_pattern() {
-  local -r pattern="$1" filename="$2" inverse="$3"
-  if [ -z "${inverse}" ]; then
-    GREP_OPTIONS= LC_ALL=C grep -nwHE "${pattern}" "${filename}"
-  else
-    # Extract matches then determine with a negative grep if they're allowed.
-    GREP_OPTIONS= LC_ALL=C grep -nwHE "${pattern}" "${filename}" \
-      | GREP_OPTIONS= LC_ALL=C grep -Ev "${inverse}"
-  fi
-}
+# Include the git setup script. This parses and normalized CLI arguments.
+. $(git --exec-path)/git-sh-setup
 
 scan() {
+  local -r file="$1"
   [ -z "${PATTERNS}" ] && return 0
   if [ -z "${ALLOWED_PATTERNS}" ]; then
-    check_pattern "${PATTERNS}" $1 && return 1 || return 0
+    # When no allowed patterns are found, we can simply do a search.
+    GREP_OPTIONS= LC_ALL=C grep -nwHE "${PATTERNS}" "${file}" && return 1
+  else
+    # Extract matches then determine with a negative grep if they're allowed.
+    GREP_OPTIONS= LC_ALL=C grep -nwHE "${PATTERNS}" "${file}" \
+      | GREP_OPTIONS= LC_ALL=C grep -Ev "${ALLOWED_PATTERNS}" && return 1
   fi
-  check_pattern "${PATTERNS}" $1 "${ALLOWED_PATTERNS}" && return 1 || return 0
+  return 0
 }
 
+# Scans all of the files in a list. Dies after scanning all if any match.
+scan_files() {
+  local found_match=0
+  for file in $@; do
+    # Skip directories
+    if [ ! -d "${file}" ]; then
+      if [ "${file}" != '-' ] && [ ! -f "${file}" ]; then
+        die "File not found: ${file}"
+      fi
+      scan "$file" || found_match=1
+    fi
+  done
+  [ "$found_match" -eq 0 ] && exit 0
+  die "$PROHIBITED_MSG"
+}
+
+# Scans a commit message, passed in the path to a file.
 commit_msg_hook() {
-  scan "$1" || die "(commit-msg)" $'\n' "$PROHIBITED_MSG"
+  scan "$1" || die "$PROHIBITED_MSG"
 }
 
-# Scans a commit for prohibited patterns.
+# Scans all files that are about to be committed.
 pre_commit_hook() {
   local file found_match=0 rev="4b825dc642cb6eb9a060e54bf8d69288fbee4904"
   # Diff against HEAD if this is not the first commit in the repo.
   [ git rev-parse --verify HEAD >/dev/null 2>&1 ] && rev="HEAD"
-  for file in $(git diff-index --name-only --cached $rev --); do
-    scan "$file" || found_match=1
-  done
-  [ $found_match -eq 0 ] && exit 0
-  die "(pre-commit)" $'\n' "$PROHIBITED_MSG"
+  scan_files "$(git diff-index --name-only --cached $rev --)"
 }
 
 # Determines if merging in a commit will introduce tainted history.
@@ -83,18 +80,15 @@ prepare_commit_msg_hook() {
       local dest="${branch#refs/heads/}"    # cut out "refs/heads"
       say "Checking if merging ${sha} into ${dest} adds prohibited history"
       git log "${dest}".."${sha}" -p \
-        | "$0" scan -f - || die "(prepare-commit-msg)" $'\n' "$PROHIBITED_MSG"
+        | "$0" --scan - || die "$PROHIBITED_MSG"
       ;;
     *) ;;
   esac
 }
 
-# Git hook installation functions
-#######################################################################
-
 # Determines the approriate path for a hook to be installed
 # This function respects any found $hook.d directories.
-determine_hook_path() {
+determine_hook_install_path() {
   local -r hook="$1" path="$2"
   local dest="${path}/.git/hooks/${hook}"
   local -r debian_dir="${path}/.git/hooks/${hook}.d"
@@ -108,48 +102,42 @@ install_hook() {
   [ -z "${dest}" ] && die "[ERR]  Expects the path to a file"
   [ -d "$(dirname ${dest})" ] || die "[ERR]  Directory not found: ${dest}"
   echo "#!/usr/bin/env bash" > "${dest}"
-  echo "git secrets ${cmd} \"\$@\"" >> "${dest}"
+  echo "git secrets --${cmd} \"\$@\"" >> "${dest}"
   chmod +x "${dest}"
   say "[OK]   Installed ${name} hook to ${dest}" $'\n'
 }
 
-install_hooks() {
+install_all_hooks() {
   local dest git_repo="$1"
-  dest=$(determine_hook_path "commit-msg" "${git_repo}")
+  dest=$(determine_hook_install_path "commit-msg" "${git_repo}")
   install_hook "${dest}" "commit-msg" "commit_msg_hook"
-  dest=$(determine_hook_path "pre-commit" "${git_repo}")
+  dest=$(determine_hook_install_path "pre-commit" "${git_repo}")
   install_hook "${dest}" "pre-commit" "pre_commit_hook"
-  dest=$(determine_hook_path "prepare-commit-msg" "${git_repo}")
+  dest=$(determine_hook_install_path "prepare-commit-msg" "${git_repo}")
   install_hook "${dest}" "prepare-commit-msg" "prepare_commit_msg_hook"
   say "Successfully installed git hooks"
 }
 
-# Dispatch to the appropriate functions
-#######################################################################
+declare -r COMMAND="$1"; shift
 
-CMD="${1:--h}"; shift
-# Determine the approriate options spec and load git-sh helpers.
-[ "$CMD" == 'scan' ] && OPTIONS_SPEC="$SCAN_SPEC"
-[ "$CMD" == 'install' ] && OPTIONS_SPEC="$INSTALL_SPEC"
-NONGIT_OK=1 # Allow the command to run outside of a git repo.
-. $(git --exec-path)/git-sh-setup
-
-case "$CMD" in
-  scan)
-    [ "$1" != '-f' ] && die "-f | --file is required"
-    [ "$2" != '-' ] && [ ! -f "$2" ] && die "File not found: $2"
-    scan "$2" || die "${PROHIBITED_MSG}"
+case "${COMMAND}" in
+  -h|--help|--) "$0" -h; exit 0 ;;
+  --commit_msg_hook|--pre_commit_hook|--prepare_commit_msg_hook)
+    # Shift off "--", which was added by git option parsing.
+    shift
+    # Strip the leading "--" from the hook function name.
+    ${COMMAND:2} "$@"
     ;;
-  install)
-    case "$1" in
-      --) dir=$(git rev-parse --show-toplevel) || die "Not in a git repo" ;;
-      -d) dir="$2" ;;
-      *) say "Invalid argument"; "$0" install -h; exit 129 ;;
-    esac
-    [ ! -d "${dir}" ] && die "Directory not found: ${dir}"
-    install_hooks "${dir}"
+  --scan)
+    [ "$1" != "--" ] && die "Unexpected argument: $1"
+    shift
+    [ $# -eq 0 ] && die "No files provided to scan"
+    scan_files "$@"
     ;;
-  commit_msg_hook|pre_commit_hook|prepare_commit_msg_hook) $CMD "$@" ;;
-  -h) printf "$MAIN_SPEC\n" ;;
-  *) echo "Unknown command: $CMD" && "$0" -h && exit 129 ;;
+  --install)
+    [ "$1" == "-d" ] && repo="$2" || repo="."
+    [ -d "${repo}" ] || die "Directory not found: ${repo}"
+    install_all_hooks "${repo}"
+    ;;
+  *) echo "Unknown option: ${option}" && "$0" -h ;;
 esac
