Support custom failure messages via git configuration

diff --git a/git-secrets b/git-secrets
--- a/git-secrets
+++ b/git-secrets
@@ -148,7 +148,21 @@ process_output() {
 scan_with_fn_or_die() {
   local fn="$1"; shift
   $fn "$@" && exit 0
+  echo_failure_message
+}
+
+# Outputs the custom failure message, or the default if no custom message
+# has been set in git config secrets.failureMessage
+echo_failure_message() {
   echo >&2
+
+  local failure_message;
+  failure_message=$(git config --get-all secrets.failureMessage)
+  if [[ $? == 0 ]]; then
+    echo -e "${failure_message}" >&2
+    exit 1
+  fi
+
   echo "[ERROR] Matched one or more prohibited patterns" >&2
   echo >&2
   echo "Possible mitigations:" >&2
